"""Remove email field from User model

Revision ID: 012087fe1f04
Revises: 4891ba3f0e99
Create Date: 2024-10-24 20:48:19.478388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '012087fe1f04'
down_revision = '4891ba3f0e99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_email', type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=False))
        batch_op.create_unique_constraint('uq_user_email', ['email'])

    # ### end Alembic commands ###
