"""Dodanie kolumny color z domyślną wartością serwerową

Revision ID: 108a9c1e4778
Revises: d5bb6cd43595
Create Date: 2024-12-17 22:06:32.171904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '108a9c1e4778'
down_revision = 'd5bb6cd43595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=7), server_default='#e0f7fa', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
