"""Add cascade delete to User relationships

Revision ID: 559da3609a8a
Revises: 65664da1e6cc
Create Date: 2024-10-22 15:31:34.849615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '559da3609a8a'
down_revision = '65664da1e6cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
