"""Add cascade delete to User relationships

Revision ID: 65664da1e6cc
Revises: 8caa70984a74
Create Date: 2024-10-22 13:44:43.467458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65664da1e6cc'
down_revision = '8caa70984a74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expiration_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_verification_code_code')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('reset_code_expiration', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_user_email_address', ['email_address'])
        batch_op.create_unique_constraint('uq_user_reset_code', ['reset_code'])
        batch_op.create_unique_constraint('uq_user_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_username', type_='unique')
        batch_op.drop_constraint('uq_user_reset_code', type_='unique')
        batch_op.drop_constraint('uq_user_email_address', type_='unique')
        batch_op.drop_column('reset_code_expiration')
        batch_op.drop_column('reset_code')

    op.drop_table('verification_code')
    # ### end Alembic commands ###
