"""Initial full schema

Revision ID: c0dfd68d7bd9
Revises: 
Create Date: 2025-01-24 00:21:21.066540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0dfd68d7bd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('license_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('revoked_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('position', sa.String(length=150), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email_address', sa.String(length=150), nullable=False),
    sa.Column('email_password', sa.String(length=500), nullable=False),
    sa.Column('app_password_hash', sa.String(length=128), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('license_key_id', sa.Integer(), nullable=False),
    sa.Column('reset_code', sa.String(length=6), nullable=True),
    sa.Column('reset_code_expiration', sa.DateTime(), nullable=True),
    sa.Column('color', sa.String(length=7), server_default='#e0f7fa', nullable=True),
    sa.ForeignKeyConstraint(['license_key_id'], ['license_key.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address', name='uq_user_email_address'),
    sa.UniqueConstraint('license_key_id', name='uq_user_license_key_id'),
    sa.UniqueConstraint('reset_code', name='uq_user_reset_code'),
    sa.UniqueConstraint('username', name='uq_user_username')
    )
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verification_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expiration_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_verification_code_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification_code')
    op.drop_table('note')
    op.drop_table('user')
    op.drop_table('license_key')
    # ### end Alembic commands ###
