"""Dodanie kolumny color do tabeli user

Revision ID: d5bb6cd43595
Revises: 2e4e5b400771
Create Date: 2024-12-17 21:50:48.876763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5bb6cd43595'
down_revision = '2e4e5b400771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=7), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
